### ISSUE TITLE
My game insta crashes after putting carpet on a slap or hanging a lantern on a wall and can't even load back to the world ever again. 

### ISSUE THREAD

**Issue by Ladiesman287** [MehVahdJukaar/amendments#131]
I am new to modding minecraft and I don't know how to fix this issue. Here is the crash report I am getting when I try to load the world again. 

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-09-14 19:13:34
Description: Tessellating block in world - Indium Renderer

java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.mehvahdjukaar.moonlight.api.client.model.CustomBakedModel.emitBlockQuads(CustomBakedModel.java:539)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bmg000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.mehvahdjukaar.moonlight.api.client.model.CustomBakedModel.emitBlockQuads(CustomBakedModel.java:539)

-- Block being tessellated --
Details:
	Block: Block{amendments:wall_lantern}[attachment=block,facing=south,light_level=15,lit=true,waterlogged=false]
	Block location: World: (-12,153,-6), Section: (at 4,9,10 in -1,9,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bmg000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Block being rendered --
Details:
	Block: Block{amendments:wall_lantern}[attachment=block,facing=south,light_level=15,lit=true,waterlogged=false]
	Block location: World: (-12,153,-6), Section: (at 4,9,10 in -1,9,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Chunk section: RenderSection at chunk (-1, 9, -1) from (-16, 144, -16) to (-1, 159, -1)
	Render context volume: class_3341{minX=-18, minY=142, minZ=-18, maxX=1, maxY=161, maxZ=1}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Uptime --
Details:
	JVM uptime: 47.111s
	Wall uptime: 32.564s
	High-res time: 27.784s
	Client ticks: 267 ticks / 13.350s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['YarasaPVP'/101, l='ClientLevel', x=-12.89, y=152.00, z=-3.98]]
	Chunk stats: 1024, 148
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,156,0), Section: (at 0,12,0 in 0,9,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 523 game time, 523 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 112

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, adventure-platform-fabric, ambientsounds, amendments, betterbeds, blur, bridgingmod, cardinal-components-base, cardinal-components-entity, carryon, catalogue, chunky, cicada, cloth-config, creativecore, distanthorizons, do_a_barrel_roll, effecttimerplus, enhancedblockentities, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, freecam, horsebuff, indium, inventoryprofilesnext, invmove, iris, item-placer, jamlib, jumpoverfences, leahs-immersive-thunder, libipn, macebut3d, midnightlib, moonlight, moreculling, nether-coords, rightclickharvest, sit, sodium, talkbubbles, toggleableitemframes, trinkets, yet_another_config_lib_v3, zoomify, moonlight:mods_dynamic_assets

**Comment by MehVahdJukaar** [comment]
It's saying that stuff from fabric itself is t there . What? See if it happens when no other mod on. If it doesn't it's not my issue.also try embeddium

**Comment by Ladiesman287** [comment]
I couldn't able to install embeddium because there is no 1.21 fabric version. Although I tried to remove the mods to try again (except distant horizon mod) and it did not work. Here is the console report right after it crashed.	


Active Data Packs: vanilla, fabric, amendments, fabric-convention-tags-v2, moonlight, moonlight:mods_dynamic_assets
	Available Data Packs: amendments, bundle, fabric, fabric-convention-tags-v2, moonlight, moonlight:mods_dynamic_assets, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -1684370981620388244

#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_23.14.53-client.txt
Here I am!
[VersionManager] Refreshing versions locally...
[Version:fabric-loader-0.15.11-1.21.1] Resolving...
[Version:fabric-loader-0.15.11-1.21.1] Inherits from 1.21.1
[Version:fabric-loader-0.16.0-1.21.1] Resolving...
[Version:fabric-loader-0.16.0-1.21.1] Inherits from 1.21.1
[VersionManager] Versions has been refreshed (9 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] [Crash] Signature "Bad video drivers" matches!
[Crash] Signature "Bad video drivers" matches!
[Launcher] [Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_19.13.34-client.txt
[Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_19.13.34-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_19.33.46-client.txt
[Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_19.33.46-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_23.12.08-client.txt
[Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_23.12.08-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_23.14.53-client.txt
[Crash] Found crash report file: C:\Users\bozo\AppData\Roaming\.minecraft\crash-reports\crash-2024-09-14_23.14.53-client.txt
[Launcher] [Crash] Crash has been recognized!
[Crash] Crash has been recognized!
flush now


> It's saying that stuff from fabric itself is t there . What? See if it happens when no other mod on. If it doesn't it's not my issue.also try embeddium

**Comment by MehVahdJukaar** [comment]
Try without any other mod, especially rendering stuff like sodium and dh

**Comment by Ladiesman287** [comment]
It worked. I removed DH and Sodium as you told, and it worked. But unfortunately I will not be able to play this beautiful mod because I really want to keep DH, and it needs Sodium to work. Although, thanks for the help. I am glad I know the reason why it's crashing.

**Comment by MehVahdJukaar** [comment]
Figure out which of the two is causing it and report to them. It's not my issue

**Comment by mothfuzz** [comment]
I'm getting the same issue - I'm using the latest version of amendments, I don't have sodium installed and Distant Horizons is disabled. You have other people reporting on this same issue in the issues page - it would be worth your time to look into it.

**Comment by MehVahdJukaar** [comment]
send latest.log as its obiously a diferent issue

**Comment by MehVahdJukaar** [comment]
closing as this is not my issue. as for the last commend a latest.log was never provided so issue is invalid
