### ISSUE TITLE
[CTD] Crash when exploring/worldgen

### ISSUE THREAD

**Issue by drakray** [MehVahdJukaar/amendments#63]
https://pastebin.com/qJXk2cVD
<details><summary>Crash Snippet</summary>

```
Description: Feature placement

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:wither_skeleton_skull}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at net.minecraft.world.level.block.SimpleWaterloggedBlock.m_7361_(SimpleWaterloggedBlock.java:25) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_230328_(StructureTemplate.java:259) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:forge_method_redirector,re:classloading,pl:accesstransformer:B,xf:fml:forge:forge_method_redirector,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_213695_(SinglePoolElement.java:124) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,re:classloading,pl:mixin:APP:waystones.mixins.json:SinglePoolElementMixin,pl:mixin:APP:mvs-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:mns-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:cyanide.common.mixins.json:accessor.SinglePoolElementAccessor,pl:mixin:APP:cyanide.common.mixins.json:SinglePoolElementMixin,pl:mixin:APP:mes-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:APP:yungsapi.mixins.json:accessor.SinglePoolElementAccessor,pl:mixin:APP:the_bumblezone-common.mixins.json:world.SinglePoolElementAccessor,pl:mixin:APP:integrated_api-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_226509_(PoolElementStructurePiece.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:APP:mns-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:APP:mes-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:APP:integrated_api-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_213694_(PoolElementStructurePiece.java:85) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:APP:mns-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:APP:mes-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:APP:integrated_api-common.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(StructureStart.java:90) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:conquered,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:conquered,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:conquered,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(ChunkGenerator.java:320) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:tlc.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:integrated_stronghold-common.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:APP:structureessentials.mixins.json:StructureSearchSpeedupMixin,pl:mixin:APP:structureessentials.mixins.json:StructureSearchTimeoutMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:idas.mixins.json:iceandfire.DisableIaFStructures,pl:mixin:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {re:mixin}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:319) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:tlc.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:integrated_stronghold-common.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:APP:structureessentials.mixins.json:StructureSearchSpeedupMixin,pl:mixin:APP:structureessentials.mixins.json:StructureSearchTimeoutMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:idas.mixins.json:iceandfire.DisableIaFStructures,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ChunkMapMixin,pl:mixin:APP:smallships-common-soft.mixins.json:leashing.ChunkMapMixin,pl:mixin:APP:tumbleweed.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23114!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ChunkMapMixin,pl:mixin:APP:smallships-common-soft.mixins.json:leashing.ChunkMapMixin,pl:mixin:APP:tumbleweed.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23920!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

```

</details>

I was getting another crash before updating to 1.1.21, about redstone_wire with -1 value, but now I get this about waterlogged wither_skeleton_skull? might be cause by a structure mod that gen it underwater?, no idea, debug.log and latest.log have zero hint

creating a new world without Amendments and exploring does not cause crash

It might be something else but I have no clue :/

Minecraft 1.20.1
NeoForge 47.1.104
Amendments 1.1.21
Supplementaries 2.8.10
Moonlight 2.11.12
BunchaOtherMods™, listed in crashlog

**Comment by drakray** [comment]
Seems fixed by 1.1.22, as I could load my world again and exploring has yet to make me crash

Thank you for your quick fix :D
