### ISSUE TITLE
An error sometimes occurs with Embeddium/Sodium

### ISSUE THREAD

**Issue by Lolothepro** [MehVahdJukaar/amendments#86]
[Amendments](https://www.curseforge.com/projects/896746) 1.20-1.1.31

log file: 
[latest.log](https://github.com/user-attachments/files/15635868/latest.log)

Error:

```
[02Jun2024 15:19:10.645] [Render thread/ERROR] [net.minecraft.util.ThreadingDetector/]: Thread dumps: 
Render thread: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.ThreadingDetector.m_199420_(ThreadingDetector.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:82)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.BitRandomSource.m_188501_(BitRandomSource.java:56)
	at TRANSFORMER/amendments@1.20-1.1.31/net.mehvahdjukaar.amendments.common.PendulumAnimation.<init>(PendulumAnimation.java:36)
	at TRANSFORMER/amendments@1.20-1.1.31/net.mehvahdjukaar.amendments.common.tile.SwayingBlockTile.<init>(SwayingBlockTile.java:24)
	at TRANSFORMER/amendments@1.20-1.1.31/net.mehvahdjukaar.amendments.common.tile.WallLanternBlockTile.<init>(WallLanternBlockTile.java:40)
	at TRANSFORMER/amendments@1.20-1.1.31/net.mehvahdjukaar.amendments.common.block.WallLanternBlock.m_142194_(WallLanternBlock.java:236)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk.m_62934_(LevelChunk.java:288)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk.m_5685_(LevelChunk.java:315)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk.m_187967_(LevelChunk.java:464)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195674_(ClientboundLevelChunkPacketData.java:107)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195660_(ClientboundLevelChunkPacketData.java:96)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk.m_187971_(LevelChunk.java:463)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientChunkCache.m_194116_(ClientChunkCache.java:112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientPacketListener.m_194198_(ClientPacketListener.java:714)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientPacketListener.m_183388_(ClientPacketListener.java:678)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:45)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:12)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.32/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.32/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.32/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[02Jun2024 15:19:10.646] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:88) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.level.levelgen.BitRandomSource.m_188501_(BitRandomSource.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.mehvahdjukaar.amendments.common.PendulumAnimation.<init>(PendulumAnimation.java:36) ~[amendments-1.20-1.1.31.jar%23157!/:?]
	at net.mehvahdjukaar.amendments.common.tile.SwayingBlockTile.<init>(SwayingBlockTile.java:24) ~[amendments-1.20-1.1.31.jar%23157!/:?]
	at net.mehvahdjukaar.amendments.common.tile.WallLanternBlockTile.<init>(WallLanternBlockTile.java:40) ~[amendments-1.20-1.1.31.jar%23157!/:?]
	at net.mehvahdjukaar.amendments.common.block.WallLanternBlock.m_142194_(WallLanternBlock.java:236) ~[amendments-1.20-1.1.31.jar%23157!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62934_(LevelChunk.java:288) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_5685_(LevelChunk.java:315) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_187967_(LevelChunk.java:464) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195674_(ClientboundLevelChunkPacketData.java:107) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195660_(ClientboundLevelChunkPacketData.java:96) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_187971_(LevelChunk.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.multiplayer.ClientChunkCache.m_194116_(ClientChunkCache.java:112) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_194198_(ClientPacketListener.java:714) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_183388_(ClientPacketListener.java:678) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:12) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.32.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.32.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.32.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:84) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	... 44 more
```

Forge 47.2.32
Minecraft 1.20.1

**Comment by MehVahdJukaar** [comment]
Please only report issues if you are using the latest mod version
